#include "led.h"

void RGB_init(){
SYSCTL_RCGCGPIO_R|=0X20;
while((SYSCTL_PRGPIO_R&0X20)==0);
GPIO_PORTF_LOCK_R=0X4C4F434B;
GPIO_PORTF_CR_R|=0X0E;
GPIO_PORTF_DIR_R|=0x0E;
GPIO_PORTF_DEN_R|=0X0E;
GPIO_PORTF_AMSEL_R&=~0x0E;// disabling analog function of PF4(SW1)
GPIO_PORTF_PCTL_R&=~0x0FFF0;
GPIO_PORTF_AFSEL_R&=~0x0E;
GPIO_PORTF_DATA_R&=~0x0E;
}

void RGB_output(unsigned char data){
	GPIO_PORTF_DATA_R&=~0x0E; //reset 3 leds ~(01110)=10001
	GPIO_PORTF_DATA_R|=data;
	
}

